on:
  check_run:
  check_suite:
  workflow_run:
    workflows: ["CI"]
    

jobs:
  get_logs:
    runs-on: ubuntu-latest
    steps:
     - run: echo Hi
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
       run: echo "$GITHUB_CONTEXT"
     - name: get logs
       env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
       run: |
        logs_url=$(echo "$GITHUB_CONTEXT" | jq -r '.event.workflow_run.logs_url')
        echo $logs_url
        jobs_url=$(echo "$GITHUB_CONTEXT" | jq -r '.event.workflow_run.jobs_url')
        echo $jobs_url
        curl -L -i -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $jobs_url
        echo ---------------------------------
        curl -L -i -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $logs_url
     
