on:
  check_run:
  check_suite:
  workflow_run:
    workflows: ["CI"]
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - run: echo Hi
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
       run: echo "$GITHUB_CONTEXT"
     - name: get logs
       env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
       run: wget $(echo "$JOB_CONTEXT" | jq -r '.event.workflow_run.logs_url')
     
